#spring.application.name=analyticsEngine
server:
  port: 8080

management:
  endpoints:
    web:
      exposure:
        include: prometheus, health, info
  metrics:
    export:
      prometheus:
        enabled: true

spring:
  kafka:
    bootstrap-servers: ${KAFKA_BROKER_URL}
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
      properties:
        spring.json.add.type.headers: true
    consumer:
      group-id: analytics-group
      auto-offset-reset: earliest
      # 1. We tell Kafka to use the ErrorHandlingDeserializer first
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.ErrorHandlingDeserializer
      properties:
        # 2. We then tell the ErrorHandlingDeserializer to use the JsonDeserializer as its 'delegate'
        spring.deserializer.value.delegate.class: org.springframework.kafka.support.serializer.JsonDeserializer
        # 3. We allow the JsonDeserializer to trust all packages (to fix your previous error)
        spring.json.trusted.packages: "*"